image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==
tasks:
  - init: python3 -m pip install --upgrade && python3 -m pip install --upgrade jupyter jupyter-client && R -e "install.packages('IRkernel', repos='http://cran.us.r-project.org')" && R -e "IRkernel::installspec()"
