image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==
    - https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
